"""add embedding_status to meeting table

Revision ID: 05548bef1ced
Revises: 922f03dfe862
Create Date: 2026-08-01 03:06:38.414940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05548bef1ced'
down_revision: Union[str, Sequence[str], None] = '922f03dfe862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('embedding_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'embedding_status')
    # ### end Alembic commands ###
