"""add title and decisions to segments

Revision ID: 71db8140ab4c
Revises: 7d1cd6fcf6f5
Create Date: 2026-07-30 13:19:15.422834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71db8140ab4c'
down_revision: Union[str, Sequence[str], None] = '7d1cd6fcf6f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('segment', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('decisions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segments_id'), 'segments', ['id'], unique=False)
    op.create_unique_constraint('unique_meeting_user', 'meeting_users', ['meeting_id', 'user_id'])
    op.alter_column('meetings', 'audio_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'audio_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('unique_meeting_user', 'meeting_users', type_='unique')
    op.drop_index(op.f('ix_segments_id'), table_name='segments')
    op.drop_table('segments')
    # ### end Alembic commands ###
