"""add transcript status

Revision ID: 7487bbd847b9
Revises: 7d1cd6fcf6f5
Create Date: 2026-07-20 22:55:14.444384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7487bbd847b9'
down_revision: Union[str, Sequence[str], None] = '7d1cd6fcf6f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_meeting_user', 'meeting_users', ['meeting_id', 'user_id'])
    op.add_column('meetings', sa.Column('transcript_status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'transcript_status')
    op.drop_constraint('unique_meeting_user', 'meeting_users', type_='unique')
    # ### end Alembic commands ###
