"""move audio relation to meeting

Revision ID: 7d1cd6fcf6f5
Revises: 9c319d7f7762
Create Date: 2026-07-19 00:25:11.396749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d1cd6fcf6f5'
down_revision: Union[str, Sequence[str], None] = '9c319d7f7762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audio_meeting_id_key'), 'audio', type_='unique')
    op.drop_constraint(op.f('audio_meeting_id_fkey'), 'audio', type_='foreignkey')
    op.drop_column('audio', 'meeting_id')
    op.add_column('meetings', sa.Column('audio_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'meetings', ['audio_id'])
    op.create_foreign_key(None, 'meetings', 'audio', ['audio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_constraint(None, 'meetings', type_='unique')
    op.drop_column('meetings', 'audio_id')
    op.add_column('audio', sa.Column('meeting_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('audio_meeting_id_fkey'), 'audio', 'meetings', ['meeting_id'], ['id'])
    op.create_unique_constraint(op.f('audio_meeting_id_key'), 'audio', ['meeting_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
