"""create meetings and meeting relations

Revision ID: cb48a00982ed
Revises: cfb1b268698f
Create Date: 2026-07-18 22:07:51.624473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb48a00982ed'
down_revision: Union[str, Sequence[str], None] = 'cfb1b268698f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=False)
    op.create_table('meeting_users',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('meeting_id', 'user_id')
    )
    op.add_column('audio', sa.Column('meeting_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'audio', ['meeting_id'])
    op.create_foreign_key(None, 'audio', 'meetings', ['meeting_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audio', type_='foreignkey')
    op.drop_constraint(None, 'audio', type_='unique')
    op.drop_column('audio', 'meeting_id')
    op.drop_table('meeting_users')
    op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
